version: "3.7"

services:
  pg_db:
    image: postgres:15.1-alpine
    container_name: pg_db
    restart: always
    environment:
      - POSTGRES_USER=&{PG_USER}
      - POSTGRES_PASSWORD=&{PG_PASSWORD}
      - POSTGRES_DB=tours
    volumes:
      - db_pg_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - pg_db

volumes:
  db_pg_volume: