version: "3.7"

services:
  backend:
    build: .
    container_name: rust_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - YOOCASSA_STORE_ID=$YOOCASSA_STORE_ID 
      - YOOCASSA_KEY=$YOOCASSA_KEY 
    ports:
      - '8090:8090'

  pg_db:
    image: postgres:15.1-alpine
    container_name: pg_db
    restart: always
    environment:
      - POSTGRES_USER=&{PG_USER}
      - POSTGRES_PASSWORD=&{PG_PASSWORD}
      - POSTGRES_DB=tours
    volumes:
      - db_pg_volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - pg_db

volumes:
  db_pg_volume: